import React from 'react';
import { MessageSquare, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion';

const CareGuideButton = ({ plant, onGenerateGuide }) => {
  return (
    <motion.div
      whileHover={{ y: -5 }}
      transition={{ type: "spring", stiffness: 400, damping: 10 }}
      className="bg-gradient-to-r from-primary-600 to-primary-500 rounded-xl shadow-lg p-6 text-white"
    >
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-xl font-semibold flex items-center">
          <MessageSquare className="w-5 h-5 mr-2" />
          AI Care Guide
        </h2>
        <Sparkles className="w-5 h-5 text-yellow-300" />
      </div>

      <p className="text-primary-100 mb-4">
        Get a personalized care guide for your {plant.common_name}{" "}
        generated by AI.
      </p>

      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={onGenerateGuide}
        className="w-full py-3 px-4 bg-white text-primary-700 rounded-lg font-medium 
          flex items-center justify-center hover:bg-primary-50 transition-colors shadow-md"
      >
        Generate Care Guide
      </motion.button>
    </motion.div>
  );
};

export default CareGuideButton;